### ISSUE TITLE
code duplication (can combine them in to one if statement with || )

### ISSUE THREAD

**Issue by RhythmGrind** [Lord-of-Bugs/cse15l-lab4-markdown-parser#2]
https://github.com/Lord-of-Bugs/cse15l-lab4-markdown-parser/blob/98587383a85a00985a63bcd754b6b13242aa6d3d/MarkdownParse.java#L16-L25

**Comment by Lord-of-Bugs** [comment]
Thank you, this is a great suggestion and I'll try to incorporate it into the source code.
